CREATE TABLE "app_settings" (
	"key" text PRIMARY KEY NOT NULL,
	"value" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "attempt_klp_results" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "attempt_klp_results_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"attempt_id" integer,
	"scenario_attempt_id" integer,
	"student_id" integer NOT NULL,
	"klp_concept_id" integer NOT NULL,
	"assessment_mode" text DEFAULT 'speaking_performance' NOT NULL,
	"support_status" text NOT NULL,
	"assessed" boolean DEFAULT true NOT NULL,
	"success_score_percent" integer DEFAULT 0 NOT NULL,
	"passed" boolean DEFAULT false NOT NULL,
	"confidence" double precision DEFAULT 1 NOT NULL,
	"raw_scores_json" jsonb DEFAULT '{}' NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "attempts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "attempts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"student_id" integer NOT NULL,
	"cycle_id" integer NOT NULL,
	"book_id" integer NOT NULL,
	"practice_task_id" integer NOT NULL,
	"timestamp" timestamp with time zone NOT NULL,
	"audio_path" text,
	"raw_transcript" text,
	"rescored_transcript" text,
	"target_match_score" double precision DEFAULT 0 NOT NULL,
	"pronunciation_score" double precision DEFAULT 0 NOT NULL,
	"fluency_score" double precision DEFAULT 0 NOT NULL,
	"completeness_score" double precision DEFAULT 0 NOT NULL,
	"consistency_score" double precision DEFAULT 0 NOT NULL,
	"composite_score" double precision DEFAULT 0 NOT NULL,
	"teacher_override_score" double precision,
	"teacher_notes" text,
	"metrics_json" jsonb
);
--> statement-breakpoint
CREATE TABLE "badges" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "badges_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" text NOT NULL,
	"name" text NOT NULL,
	"description" text NOT NULL,
	"icon" text NOT NULL,
	"xp_reward" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "badges_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "books" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "books_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"cefr_level" text DEFAULT 'A1' NOT NULL,
	"total_words" integer DEFAULT 180 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "custom_practice_sets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "custom_practice_sets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"cycle_id" integer NOT NULL,
	"created_by_user_id" integer NOT NULL,
	"word_ids" jsonb DEFAULT '[]' NOT NULL,
	"task_types" jsonb DEFAULT '[]' NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cycles" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cycles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"start_date" date NOT NULL,
	"end_date" date NOT NULL,
	"book_id" integer NOT NULL,
	"teacher_notes" text
);
--> statement-breakpoint
CREATE TABLE "daily_goals" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "daily_goals_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"student_id" integer NOT NULL,
	"date" date NOT NULL,
	"target_words" integer DEFAULT 10 NOT NULL,
	"completed_words" integer DEFAULT 0 NOT NULL,
	"completed" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "dashboard_widgets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "dashboard_widgets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"widget_config" jsonb DEFAULT '[]' NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"active_tab" text DEFAULT 'practice' NOT NULL,
	"collapsed_sections_json" jsonb DEFAULT '[]' NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "external_identities" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "external_identities_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"provider" text NOT NULL,
	"subject" text NOT NULL,
	"user_account_id" integer NOT NULL,
	"role" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"last_login_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "external_sso_launches" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "external_sso_launches_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"provider" text NOT NULL,
	"jti" text NOT NULL,
	"user_account_id" integer,
	"created_at" timestamp with time zone NOT NULL,
	"expires_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "fluency_drill_sessions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fluency_drill_sessions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"student_id" integer NOT NULL,
	"cycle_id" integer,
	"drill_type" text NOT NULL,
	"topic_id" text,
	"rounds_json" jsonb DEFAULT '[]' NOT NULL,
	"improvement_score" double precision DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "homework_assignments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "homework_assignments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"cycle_id" integer NOT NULL,
	"created_by_user_id" integer NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"word_ids" jsonb DEFAULT '[]' NOT NULL,
	"task_types" jsonb DEFAULT '[]' NOT NULL,
	"due_date" date NOT NULL,
	"class_name" text,
	"target_type" text DEFAULT 'class' NOT NULL,
	"student_ids_json" jsonb DEFAULT '[]' NOT NULL,
	"klp_ids_json" jsonb DEFAULT '[]' NOT NULL,
	"scenario_ids_json" jsonb DEFAULT '[]' NOT NULL,
	"source" text DEFAULT 'manual' NOT NULL,
	"status" text DEFAULT 'assigned' NOT NULL,
	"path_config_json" jsonb,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "homework_path_progress" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "homework_path_progress_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"homework_id" integer NOT NULL,
	"student_id" integer NOT NULL,
	"stage_key" text NOT NULL,
	"status" text DEFAULT 'locked' NOT NULL,
	"completed_items_json" jsonb DEFAULT '[]' NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "homework_submissions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "homework_submissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"homework_id" integer NOT NULL,
	"student_id" integer NOT NULL,
	"completed_at" timestamp with time zone,
	"words_completed" integer DEFAULT 0 NOT NULL,
	"avg_score" double precision DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "klp_active_question_shapes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "klp_active_question_shapes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"source_id" integer NOT NULL,
	"question_id" text NOT NULL,
	"concept_id" text NOT NULL,
	"question_shape" text NOT NULL,
	"modality" text,
	"raw_json" jsonb DEFAULT '{}' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "klp_concepts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "klp_concepts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"source_id" integer NOT NULL,
	"concept_id" text NOT NULL,
	"book" text,
	"lesson" text,
	"domain" text NOT NULL,
	"concept_number" text,
	"subdivision" text,
	"base_item" text,
	"subtype" text,
	"part_of_speech" text,
	"definition" text,
	"dli_classification" text,
	"primary_skill_type" text,
	"secondary_skill_type" text,
	"tertiary_skill_type" text,
	"quaternary_skill_type" text,
	"duplicate_in_course" text,
	"duplicate_in_book" text,
	"support_status" text DEFAULT 'unsupported' NOT NULL,
	"active_question_count" integer DEFAULT 0 NOT NULL,
	"active_question_shapes_json" jsonb DEFAULT '[]' NOT NULL,
	"raw_json" jsonb DEFAULT '{}' NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "klp_generated_scenarios" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "klp_generated_scenarios_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"scenario_id" text NOT NULL,
	"title" text NOT NULL,
	"description" text NOT NULL,
	"cefr_level" text DEFAULT 'A1' NOT NULL,
	"icon" text DEFAULT 'Drama' NOT NULL,
	"ai_role" text NOT NULL,
	"student_goal" text NOT NULL,
	"system_prompt" text NOT NULL,
	"first_message" text NOT NULL,
	"success_criteria_json" jsonb DEFAULT '[]' NOT NULL,
	"target_vocabulary_json" jsonb DEFAULT '[]' NOT NULL,
	"min_turns" integer DEFAULT 4 NOT NULL,
	"max_turns" integer DEFAULT 8 NOT NULL,
	"progression_mode" text DEFAULT 'guided' NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"source" text DEFAULT 'ai_klp' NOT NULL,
	"created_by_user_id" integer,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"published_at" timestamp with time zone,
	"klp_ids_json" jsonb DEFAULT '[]' NOT NULL,
	CONSTRAINT "klp_generated_scenarios_scenario_id_unique" UNIQUE("scenario_id")
);
--> statement-breakpoint
CREATE TABLE "klp_import_sources" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "klp_import_sources_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"file_name" text,
	"imported_at" timestamp with time zone NOT NULL,
	"imported_by_user_id" integer,
	"total_concepts" integer DEFAULT 0 NOT NULL,
	"active_question_shapes" integer DEFAULT 0 NOT NULL,
	"warnings_json" jsonb DEFAULT '[]' NOT NULL,
	"status" text DEFAULT 'imported' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "live_sessions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "live_sessions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"cycle_id" integer NOT NULL,
	"created_by_user_id" integer NOT NULL,
	"started_at" timestamp with time zone NOT NULL,
	"ended_at" timestamp with time zone,
	"task_type" text NOT NULL,
	"word_ids" jsonb DEFAULT '[]' NOT NULL,
	"class_name" text
);
--> statement-breakpoint
CREATE TABLE "practice_task_klps" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "practice_task_klps_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"practice_task_id" integer NOT NULL,
	"klp_concept_id" integer NOT NULL,
	"assessment_mode" text DEFAULT 'speaking_performance' NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "practice_tasks" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "practice_tasks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"book_id" integer NOT NULL,
	"vocabulary_item_id" integer,
	"task_type" text NOT NULL,
	"prompt" text NOT NULL,
	"expected_answers" jsonb,
	"pass_score" double precision DEFAULT 0.6 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "scenario_attempts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "scenario_attempts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"student_id" integer NOT NULL,
	"scenario_id" text NOT NULL,
	"transcript_json" jsonb DEFAULT '[]' NOT NULL,
	"criteria_met_json" jsonb DEFAULT '[]' NOT NULL,
	"score" double precision DEFAULT 0 NOT NULL,
	"feedback" text,
	"session_id" text,
	"learner_turns" integer DEFAULT 0 NOT NULL,
	"completion_reason" text,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "scenario_klps" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "scenario_klps_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"scenario_id" text NOT NULL,
	"klp_concept_id" integer NOT NULL,
	"assessment_mode" text DEFAULT 'speaking_performance' NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sessions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sessions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"token_hash" text NOT NULL,
	"user_id" integer NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	CONSTRAINT "sessions_token_hash_unique" UNIQUE("token_hash")
);
--> statement-breakpoint
CREATE TABLE "spaced_repetition_queue" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "spaced_repetition_queue_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"student_id" integer NOT NULL,
	"vocabulary_item_id" integer NOT NULL,
	"cycle_id" integer NOT NULL,
	"interval" integer DEFAULT 1 NOT NULL,
	"ease_factor" double precision DEFAULT 2.5 NOT NULL,
	"repetitions" integer DEFAULT 0 NOT NULL,
	"next_review_date" date NOT NULL,
	"last_review_date" date
);
--> statement-breakpoint
CREATE TABLE "speech_reliability_events" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "speech_reliability_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"student_id" integer,
	"user_id" integer,
	"class_name" text,
	"event_type" text NOT NULL,
	"provider" text NOT NULL,
	"route" text NOT NULL,
	"practice_stage" text,
	"scenario_id" text,
	"practice_task_id" integer,
	"success" boolean DEFAULT false NOT NULL,
	"status_code" integer,
	"error_code" text,
	"latency_ms" integer DEFAULT 0 NOT NULL,
	"no_speech" boolean DEFAULT false NOT NULL,
	"fallback_used" boolean DEFAULT false NOT NULL,
	"metadata_json" jsonb DEFAULT '{}' NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stage_overrides" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stage_overrides_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"student_id" integer NOT NULL,
	"cycle_id" integer NOT NULL,
	"task_type" text NOT NULL,
	"unlocked" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "student_badges" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "student_badges_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"student_id" integer NOT NULL,
	"badge_id" integer NOT NULL,
	"earned_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "student_cycles" (
	"student_id" integer NOT NULL,
	"cycle_id" integer NOT NULL,
	"enrolled_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "student_klp_summaries" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "student_klp_summaries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"student_id" integer NOT NULL,
	"klp_concept_id" integer NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"successes" integer DEFAULT 0 NOT NULL,
	"latest_score_percent" integer DEFAULT 0 NOT NULL,
	"last_practiced_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "student_texts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "student_texts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"student_id" integer NOT NULL,
	"title" text NOT NULL,
	"original_text" text NOT NULL,
	"summary" text,
	"word_count" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"last_practiced_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "student_word_lists" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "student_word_lists_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"student_id" integer NOT NULL,
	"name" text NOT NULL,
	"words" jsonb DEFAULT '[]' NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"last_practiced_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "student_xp" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "student_xp_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"student_id" integer NOT NULL,
	"amount" integer NOT NULL,
	"reason" text NOT NULL,
	"earned_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "students" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "students_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"unique_number" text NOT NULL,
	"full_name" text NOT NULL,
	"class" text,
	"cefr_band" text DEFAULT 'A1' NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"notes" text,
	"diagnostic_json" jsonb,
	"onboarded_at" timestamp with time zone,
	CONSTRAINT "students_unique_number_unique" UNIQUE("unique_number")
);
--> statement-breakpoint
CREATE TABLE "teacher_flags" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "teacher_flags_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"attempt_id" integer,
	"student_id" integer,
	"flag_type" text NOT NULL,
	"notes" text,
	"created_at" timestamp with time zone NOT NULL,
	"resolved_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "text_attempts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "text_attempts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"student_text_id" integer NOT NULL,
	"student_id" integer NOT NULL,
	"spoken_transcript" text,
	"accuracy_score" double precision DEFAULT 0 NOT NULL,
	"pronunciation_score" double precision DEFAULT 0 NOT NULL,
	"fluency_score" double precision DEFAULT 0 NOT NULL,
	"completeness_score" double precision DEFAULT 0 NOT NULL,
	"weak_words" jsonb DEFAULT '[]' NOT NULL,
	"attempted_at" timestamp with time zone NOT NULL,
	"duration_seconds" double precision DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_accounts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_accounts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"username" text NOT NULL,
	"password_hash" text NOT NULL,
	"role" text DEFAULT 'Student' NOT NULL,
	"student_id" integer,
	"display_name" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"must_change_password" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"last_login_at" timestamp with time zone,
	CONSTRAINT "user_accounts_username_unique" UNIQUE("username")
);
--> statement-breakpoint
CREATE TABLE "vocabulary_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vocabulary_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"book_id" integer NOT NULL,
	"word" text NOT NULL,
	"arabic_meaning" text,
	"phoneme_string" text,
	"difficulty_tier" integer DEFAULT 1 NOT NULL,
	"unit" integer DEFAULT 1 NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"sentence_frames" jsonb,
	"part_of_speech" text,
	"example_sentence" text
);
--> statement-breakpoint
CREATE TABLE "word_mastery_records" (
	"student_id" integer NOT NULL,
	"vocabulary_item_id" integer NOT NULL,
	"cycle_id" integer NOT NULL,
	"times_seen" integer DEFAULT 0 NOT NULL,
	"times_spoken" integer DEFAULT 0 NOT NULL,
	"best_score" double precision DEFAULT 0 NOT NULL,
	"latest_score" double precision DEFAULT 0 NOT NULL,
	"mastery_status" text DEFAULT 'NotStarted' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "xapi_outbox" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "xapi_outbox_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"statement_id" text NOT NULL,
	"attempt_klp_result_id" integer NOT NULL,
	"student_id" integer NOT NULL,
	"actor_subject" text NOT NULL,
	"verb" text NOT NULL,
	"statement_json" jsonb NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"next_attempt_at" timestamp with time zone NOT NULL,
	"last_attempt_at" timestamp with time zone,
	"sent_at" timestamp with time zone,
	"last_error" text,
	"response_status" integer,
	"locked_at" timestamp with time zone,
	"lock_owner" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "xapi_outbox_statement_id_unique" UNIQUE("statement_id")
);
--> statement-breakpoint
ALTER TABLE "attempt_klp_results" ADD CONSTRAINT "attempt_klp_results_attempt_id_attempts_id_fk" FOREIGN KEY ("attempt_id") REFERENCES "public"."attempts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attempt_klp_results" ADD CONSTRAINT "attempt_klp_results_scenario_attempt_id_scenario_attempts_id_fk" FOREIGN KEY ("scenario_attempt_id") REFERENCES "public"."scenario_attempts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attempt_klp_results" ADD CONSTRAINT "attempt_klp_results_student_id_students_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attempt_klp_results" ADD CONSTRAINT "attempt_klp_results_klp_concept_id_klp_concepts_id_fk" FOREIGN KEY ("klp_concept_id") REFERENCES "public"."klp_concepts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attempts" ADD CONSTRAINT "attempts_student_id_students_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attempts" ADD CONSTRAINT "attempts_cycle_id_cycles_id_fk" FOREIGN KEY ("cycle_id") REFERENCES "public"."cycles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attempts" ADD CONSTRAINT "attempts_book_id_books_id_fk" FOREIGN KEY ("book_id") REFERENCES "public"."books"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attempts" ADD CONSTRAINT "attempts_practice_task_id_practice_tasks_id_fk" FOREIGN KEY ("practice_task_id") REFERENCES "public"."practice_tasks"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "custom_practice_sets" ADD CONSTRAINT "custom_practice_sets_cycle_id_cycles_id_fk" FOREIGN KEY ("cycle_id") REFERENCES "public"."cycles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cycles" ADD CONSTRAINT "cycles_book_id_books_id_fk" FOREIGN KEY ("book_id") REFERENCES "public"."books"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "daily_goals" ADD CONSTRAINT "daily_goals_student_id_students_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dashboard_widgets" ADD CONSTRAINT "dashboard_widgets_user_id_user_accounts_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user_accounts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "external_identities" ADD CONSTRAINT "external_identities_user_account_id_user_accounts_id_fk" FOREIGN KEY ("user_account_id") REFERENCES "public"."user_accounts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "external_sso_launches" ADD CONSTRAINT "external_sso_launches_user_account_id_user_accounts_id_fk" FOREIGN KEY ("user_account_id") REFERENCES "public"."user_accounts"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fluency_drill_sessions" ADD CONSTRAINT "fluency_drill_sessions_student_id_students_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fluency_drill_sessions" ADD CONSTRAINT "fluency_drill_sessions_cycle_id_cycles_id_fk" FOREIGN KEY ("cycle_id") REFERENCES "public"."cycles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "homework_assignments" ADD CONSTRAINT "homework_assignments_cycle_id_cycles_id_fk" FOREIGN KEY ("cycle_id") REFERENCES "public"."cycles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "homework_path_progress" ADD CONSTRAINT "homework_path_progress_homework_id_homework_assignments_id_fk" FOREIGN KEY ("homework_id") REFERENCES "public"."homework_assignments"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "homework_path_progress" ADD CONSTRAINT "homework_path_progress_student_id_students_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "homework_submissions" ADD CONSTRAINT "homework_submissions_homework_id_homework_assignments_id_fk" FOREIGN KEY ("homework_id") REFERENCES "public"."homework_assignments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "homework_submissions" ADD CONSTRAINT "homework_submissions_student_id_students_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "klp_active_question_shapes" ADD CONSTRAINT "klp_active_question_shapes_source_id_klp_import_sources_id_fk" FOREIGN KEY ("source_id") REFERENCES "public"."klp_import_sources"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "klp_concepts" ADD CONSTRAINT "klp_concepts_source_id_klp_import_sources_id_fk" FOREIGN KEY ("source_id") REFERENCES "public"."klp_import_sources"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "live_sessions" ADD CONSTRAINT "live_sessions_cycle_id_cycles_id_fk" FOREIGN KEY ("cycle_id") REFERENCES "public"."cycles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "practice_task_klps" ADD CONSTRAINT "practice_task_klps_practice_task_id_practice_tasks_id_fk" FOREIGN KEY ("practice_task_id") REFERENCES "public"."practice_tasks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "practice_task_klps" ADD CONSTRAINT "practice_task_klps_klp_concept_id_klp_concepts_id_fk" FOREIGN KEY ("klp_concept_id") REFERENCES "public"."klp_concepts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "practice_tasks" ADD CONSTRAINT "practice_tasks_book_id_books_id_fk" FOREIGN KEY ("book_id") REFERENCES "public"."books"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "practice_tasks" ADD CONSTRAINT "practice_tasks_vocabulary_item_id_vocabulary_items_id_fk" FOREIGN KEY ("vocabulary_item_id") REFERENCES "public"."vocabulary_items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "scenario_attempts" ADD CONSTRAINT "scenario_attempts_student_id_students_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "scenario_klps" ADD CONSTRAINT "scenario_klps_klp_concept_id_klp_concepts_id_fk" FOREIGN KEY ("klp_concept_id") REFERENCES "public"."klp_concepts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_user_accounts_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user_accounts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "spaced_repetition_queue" ADD CONSTRAINT "spaced_repetition_queue_student_id_students_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "spaced_repetition_queue" ADD CONSTRAINT "spaced_repetition_queue_vocabulary_item_id_vocabulary_items_id_fk" FOREIGN KEY ("vocabulary_item_id") REFERENCES "public"."vocabulary_items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "spaced_repetition_queue" ADD CONSTRAINT "spaced_repetition_queue_cycle_id_cycles_id_fk" FOREIGN KEY ("cycle_id") REFERENCES "public"."cycles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "speech_reliability_events" ADD CONSTRAINT "speech_reliability_events_student_id_students_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "speech_reliability_events" ADD CONSTRAINT "speech_reliability_events_practice_task_id_practice_tasks_id_fk" FOREIGN KEY ("practice_task_id") REFERENCES "public"."practice_tasks"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stage_overrides" ADD CONSTRAINT "stage_overrides_student_id_students_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stage_overrides" ADD CONSTRAINT "stage_overrides_cycle_id_cycles_id_fk" FOREIGN KEY ("cycle_id") REFERENCES "public"."cycles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_badges" ADD CONSTRAINT "student_badges_student_id_students_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_badges" ADD CONSTRAINT "student_badges_badge_id_badges_id_fk" FOREIGN KEY ("badge_id") REFERENCES "public"."badges"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_cycles" ADD CONSTRAINT "student_cycles_student_id_students_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_cycles" ADD CONSTRAINT "student_cycles_cycle_id_cycles_id_fk" FOREIGN KEY ("cycle_id") REFERENCES "public"."cycles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_klp_summaries" ADD CONSTRAINT "student_klp_summaries_student_id_students_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_klp_summaries" ADD CONSTRAINT "student_klp_summaries_klp_concept_id_klp_concepts_id_fk" FOREIGN KEY ("klp_concept_id") REFERENCES "public"."klp_concepts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_texts" ADD CONSTRAINT "student_texts_student_id_students_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_word_lists" ADD CONSTRAINT "student_word_lists_student_id_students_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_xp" ADD CONSTRAINT "student_xp_student_id_students_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "teacher_flags" ADD CONSTRAINT "teacher_flags_attempt_id_attempts_id_fk" FOREIGN KEY ("attempt_id") REFERENCES "public"."attempts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "teacher_flags" ADD CONSTRAINT "teacher_flags_student_id_students_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "text_attempts" ADD CONSTRAINT "text_attempts_student_text_id_student_texts_id_fk" FOREIGN KEY ("student_text_id") REFERENCES "public"."student_texts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "text_attempts" ADD CONSTRAINT "text_attempts_student_id_students_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_accounts" ADD CONSTRAINT "user_accounts_student_id_students_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vocabulary_items" ADD CONSTRAINT "vocabulary_items_book_id_books_id_fk" FOREIGN KEY ("book_id") REFERENCES "public"."books"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "word_mastery_records" ADD CONSTRAINT "word_mastery_records_student_id_students_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "word_mastery_records" ADD CONSTRAINT "word_mastery_records_vocabulary_item_id_vocabulary_items_id_fk" FOREIGN KEY ("vocabulary_item_id") REFERENCES "public"."vocabulary_items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "word_mastery_records" ADD CONSTRAINT "word_mastery_records_cycle_id_cycles_id_fk" FOREIGN KEY ("cycle_id") REFERENCES "public"."cycles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "xapi_outbox" ADD CONSTRAINT "xapi_outbox_attempt_klp_result_id_attempt_klp_results_id_fk" FOREIGN KEY ("attempt_klp_result_id") REFERENCES "public"."attempt_klp_results"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "xapi_outbox" ADD CONSTRAINT "xapi_outbox_student_id_students_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "external_identities_provider_subject_idx" ON "external_identities" USING btree ("provider","subject");--> statement-breakpoint
CREATE UNIQUE INDEX "external_sso_launches_provider_jti_idx" ON "external_sso_launches" USING btree ("provider","jti");--> statement-breakpoint
CREATE UNIQUE INDEX "homework_path_progress_assignment_student_stage_idx" ON "homework_path_progress" USING btree ("homework_id","student_id","stage_key");--> statement-breakpoint
CREATE INDEX "klp_active_questions_source_question_lookup_idx" ON "klp_active_question_shapes" USING btree ("source_id","question_id");--> statement-breakpoint
CREATE UNIQUE INDEX "klp_concepts_source_concept_idx" ON "klp_concepts" USING btree ("source_id","concept_id");--> statement-breakpoint
CREATE UNIQUE INDEX "practice_task_klps_task_concept_idx" ON "practice_task_klps" USING btree ("practice_task_id","klp_concept_id");--> statement-breakpoint
CREATE UNIQUE INDEX "scenario_attempts_session_idx" ON "scenario_attempts" USING btree ("session_id");--> statement-breakpoint
CREATE UNIQUE INDEX "scenario_klps_scenario_concept_idx" ON "scenario_klps" USING btree ("scenario_id","klp_concept_id");--> statement-breakpoint
CREATE INDEX "speech_reliability_created_at_idx" ON "speech_reliability_events" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "speech_reliability_student_idx" ON "speech_reliability_events" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "speech_reliability_class_idx" ON "speech_reliability_events" USING btree ("class_name");--> statement-breakpoint
CREATE INDEX "speech_reliability_event_type_idx" ON "speech_reliability_events" USING btree ("event_type");--> statement-breakpoint
CREATE UNIQUE INDEX "student_klp_summaries_student_concept_idx" ON "student_klp_summaries" USING btree ("student_id","klp_concept_id");--> statement-breakpoint
CREATE INDEX "xapi_outbox_status_next_attempt_idx" ON "xapi_outbox" USING btree ("status","next_attempt_at");--> statement-breakpoint
CREATE INDEX "xapi_outbox_result_idx" ON "xapi_outbox" USING btree ("attempt_klp_result_id");